# File with three sets of data and plots
```{r, echo=FALSE, warning=FALSE, include=FALSE}
#Multiplots:
#From: http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


```{r, echo=FALSE, warning=FALSE, include=FALSE}
#Evolution Pop's: Activity

source("~/Bioinformatics/Long_Term_Data/Data_LongTermPopulationExperiments_Git/Predation_ActivityAggregation/scripts/PredationActivityAnalysisJune2015.R")

#Nieve Flies: Activity

source("~/Bioinformatics/Long_Term_Data/Data_LongTermPopulationExperiments_Git/Predation_ActivityAggregation/scripts/ActivityDrosophila_SpiderCues_Nieve.R")


#Evolved Pop's: Mating Behaviours

source("~/Bioinformatics/Long_Term_Data/Data_LongTermPopulationExperiments_Git/PredationCourtship/scripts/AP_data_R_script.R")
```




###Evolved Activity (light:dark)

```{r, echo=FALSE, warning=FALSE}
with(dat.hourly[dat.hourly$Trt=="C",], 
    plot(Hourly_activity ~ jitter(hour.shifted, factor=1.3), pch=20, cex=0.2,
         xlab ="hours after initiation", ylab = "hourly activity",
         main = "temporal patterns of activity ",
         ylim=c(0,800)))
         
with(dat.hourly[dat.hourly$Trt=="C",], lines(smooth.spline(y=Hourly_activity, x = hour.shifted),lwd=2))

with(dat.hourly[dat.hourly$Trt=="P",], points(Hourly_activity ~ jitter(hour.shifted, factor=1.3), pch=20, cex=0.2, col="red"))
with(dat.hourly[dat.hourly$Trt=="P",], lines(smooth.spline(y=Hourly_activity, x = hour.shifted), col="red", lwd=2))

with(dat.hourly[dat.hourly$Trt=="S",], points(Hourly_activity ~ jitter(hour.shifted, factor=1.3), pch=20, cex=0.2, col="blue"))
with(dat.hourly[dat.hourly$Trt=="S",], lines(smooth.spline(y=Hourly_activity, x = hour.shifted), col="blue", lwd=2))

legend(x=21, y=820, legend=c("LTC", "LTP", "LTS"), pch=20, col=c(1, "red", "blue"))
rect(xleft=2, xright=14, ybottom = 0, ytop = 830, col="#ffff0032", border=NA)

```


###Nieve Mean Daily Activity: By monitor and combined

```{r, echo=FALSE, warning=FALSE}
g1 <- plo2+geom_boxplot()
g2 <- plo3+geom_boxplot()
multiplot(g1, g2, cols = 2)
```

###Very Quick linear model for daily activity

```{r, warning=FALSE}
day_act.lmer <- lmer(mean_activity ~ Treatment + monitor + (1|day), data=day_act)
car::Anova(day_act.lmer)
summary(day_act.lmer)
confint(day_act.lmer)
```


###Courtship and Copulation Plots for evolved populations:

Population Mean plots:

```{r, echo=FALSE, warning=FALSE}

copplot <- p1+geom_boxplot()
Courtlat<-p2+geom_boxplot()
coplat <- p3+geom_boxplot()
copdur<-p4+geom_boxplot()
multiplot(copplot, Courtlat, coplat, copdur, cols=2)
```

Population plots together:

```{r, echo=FALSE, warning=FALSE}
Rel_court <- p6+geom_boxplot()
Rel_coplat <- p7+geom_boxplot()
Rel_copdur <- p8+geom_boxplot()
multiplot(Rel_court, Rel_coplat, Rel_copdur, cols=2)
```

Replicates Split:

```{r, echo=FALSE, warning=FALSE}
Rel_court_Rep <- p10+geom_boxplot()
Rel_coplat_Rep <- p11+geom_boxplot()
Rel_copdur_Rep <- p12+geom_boxplot()
multiplot(Rel_court_Rep, Rel_coplat_Rep, Rel_copdur_Rep, cols=2)
```




