### Analysis of social aggregation of Drosophila adults after experimental evolution with predators (control, mantid or spider)


# Notes
# From AS:
# Note that days 1-7 were from the first replicate (late May), and days 8-15 were from the second (mid June). For "Treatment", 0=control, 1=mantis, 2=spider. For "Sex", 1=male, 2=female.

# The median and mean NN distance values in the last two columns are scaled to the diameter of each dish and are in millimeters.

# Note from RD: 
# I would focus on the median NND scaled - the penultimate column. Also, the file name is misleading - this is the comparison between the 12 populations, with focal flies being second generation with no predation. 

# Notes from ID:
# There were 4 boxes (each with a single camera) used. IN each box there were 6 plates used. A balanced randomized design was used with constraints such that distinct populations were in each box, and equal sexes (3 plates with M, 3 plates with F). Since boxes may have some distinct features (lighting, position, etc) it may be worth treating this blocking effect as fixed (also, only 4 levels). Since all populations (and sexes) were done in each box,do not nest pop in box.

# date should be a random effect. I think just modeling variation out of the intercept (1|date) should be sufficient for this model.

# For the temporal effect, both a fixed effect of time and probably a plate specific (1+time|plate) sort of term may help. Maybe a time:treatment effect as well?

# There is no column specified for plate. This can be generated by generating a new factor for combinining treatment:pop:sex:day:box... 

#libraries
library(lme4)
library(car)
library(effects)
# Please start analysis in the scripts folder...
social_dat <- read.csv("../data/Social_behaviour_under_predation_Full_data.csv", h=T)

# Alter the codings for analysis (from the numeric dummy codes, to biologically meaningful ones.)
table(social_dat$Treatment)
social_dat$Treatment2 <- factor(social_dat$Treatment, labels=c("control", "mantis", "spider"))
social_dat$Sex2 <- factor(social_dat$Sex, labels=c("male", "female"))
social_dat$Day <- factor(social_dat$Day)
social_dat$Box <- factor(social_dat$Box)
social_dat$Population <- factor(social_dat$Population)

# Create a variable for each dish.

social_dat$dish <- with(social_dat, interaction(Treatment2, Sex2, Day, Population, Box, drop=TRUE))
#check each dish has 60 records
nlevels(social_dat$dish)
sum(table(social_dat$dish) ==60)

# plotting to check for outliers, skew, etc...
hist(social_dat$medianNNDscaled_mm)
summary(social_dat$medianNNDscaled_mm)
boxplot(social_dat$medianNNDscaled_mm ~ social_dat$Sex2)
boxplot(social_dat$medianNNDscaled_mm ~ social_dat$Treatment2)
boxplot(social_dat$medianNNDscaled_mm ~ social_dat$Day) # Check that results are robust to the dip in day8.
boxplot(social_dat$medianNNDscaled_mm ~ social_dat$Box)
lattice::bwplot(social_dat$medianNNDscaled_mm ~ social_dat$Treatment2|social_dat$Sex2)

with(social_dat, 
    plot(x = medianNNDscaled_mm, y = meanNNDscaled_mm, col=densCols(x= medianNNDscaled_mm, y = meanNNDscaled_mm)))
    
with(social_dat[social_dat$Treatment2== "control",], plot(medianNNDscaled_mm, meanNNDscaled_mm))
with(social_dat[social_dat$Treatment2== "mantis",], plot(medianNNDscaled_mm, meanNNDscaled_mm))
with(social_dat[social_dat$Treatment2== "spider",], plot(medianNNDscaled_mm, meanNNDscaled_mm))

hist(social_dat$medianNNDscaled_mm[social_dat$Treatment2 == "control"], main="control")
hist(social_dat$medianNNDscaled_mm[social_dat$Treatment2 == "mantis"], main="mantis")
hist(social_dat$medianNNDscaled_mm[social_dat$Treatment2 == "spider"], main="spider")

hist(social_dat$medianNNDscaled_mm[social_dat$Sex2 == "male"], main="male")
hist(social_dat$medianNNDscaled_mm[social_dat$Sex2 == "female"], main="female")

hist(social_dat$medianNNDscaled_mm[social_dat$Box == 1])
hist(social_dat$medianNNDscaled_mm[social_dat$Box == 2])
hist(social_dat$medianNNDscaled_mm[social_dat$Box == 3])
hist(social_dat$medianNNDscaled_mm[social_dat$Box == 4])

# overall relationship with time
with(social_dat, plot( y = medianNNDscaled_mm, x = Time))
with(social_dat, plot( y = medianNNDscaled_mm, x = Time, pch=20, col = densCols(x= Time, y = medianNNDscaled_mm )))
with(social_dat, lines(smooth.spline(y = medianNNDscaled_mm, x = Time, cv=FALSE, spar=0.5), lwd=3, col="red"))

# wow, so the data appears pretty well behaved (in the sense of no strong outliers, or weirdness)

# Now for the model.

aggregation_lmm1 <- lmer(medianNNDscaled_mm ~ ( Sex2 + Time + Treatment2)^2 + Box + (1|Treatment2:Population) + (1| Day), data= social_dat)

summary(aggregation_lmm1)
Anova(aggregation_lmm1)
plot(allEffects(aggregation_lmm1))

aggregation_lmm2 <- lmer(medianNNDscaled_mm ~ (Sex2 + Time + Treatment2)^2 + Box + (1|Treatment2:Population) + (1| Day) + (1|dish), data= social_dat)

summary(aggregation_lmm2)
Anova(aggregation_lmm2)
plot(allEffects(aggregation_lmm2))

aggregation_lmm3 <- lmer(medianNNDscaled_mm ~ Treatment2 + Sex2 + Time + Time:Sex2 + Box + (1|Treatment2:Population) + (1| Day) + (1|dish), data= social_dat)

summary(aggregation_lmm3)
Anova(aggregation_lmm3)


aggregation_lmm4 <- lmer(medianNNDscaled_mm ~ (Treatment2 + Sex2 + Time)^2 + Box + (1|Treatment2:Population) + (1 | Day) + (1 + Time|dish), data= social_dat)

summary(aggregation_lmm4)
Anova(aggregation_lmm4)
plot(allEffects(aggregation_lmm4))

aggregation_lmm5 <- lmer(medianNNDscaled_mm ~ Treatment2 + Sex2*Time  + Box + (1|Treatment2:Population) + (1 | Day) + (1 + Time|dish), data= social_dat)

summary(aggregation_lmm5)
Anova(aggregation_lmm5)
plot(allEffects(aggregation_lmm5))

REMLcrit(aggregation_lmm1)
REMLcrit(aggregation_lmm2)
REMLcrit(aggregation_lmm3)
REMLcrit(aggregation_lmm4)
AIC(aggregation_lmm3)
AIC(aggregation_lmm4)